// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace DebugMcp.E2E.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BreakpointsFeature : object, global::Xunit.IClassFixture<BreakpointsFeature.FixtureData>, global::Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features", "Breakpoints", "    As a debugger user\n    I want to set and manage breakpoints\n    So that I can" +
                " pause execution at specific code locations", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
        private global::Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "Breakpoints.feature"
#line hidden
        
        public BreakpointsFeature(BreakpointsFeature.FixtureData fixtureData, global::Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages("Features/Breakpoints.feature.ndjson", 13);
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((global::Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set a breakpoint and hit it during execution")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Set a breakpoint and hit it during execution")]
        public async global::System.Threading.Tasks.Task SetABreakpointAndHitItDuringExecution()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set a breakpoint and hit it during execution", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 6
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 9
        await testRunner.AndAsync("a breakpoint on \"MethodTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 10
        await testRunner.WhenAsync("the test target executes the \"method\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
        await testRunner.AndAsync("I wait for a breakpoint hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 12
        await testRunner.ThenAsync("the debugger should pause at \"MethodTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
        await testRunner.AndAsync("the session state should be \"Paused\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Conditional breakpoint with hit count")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Conditional breakpoint with hit count")]
        public async global::System.Threading.Tasks.Task ConditionalBreakpointWithHitCount()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Conditional breakpoint with hit count", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 16
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 17
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 18
        await testRunner.AndAsync("a conditional breakpoint on \"LoopTarget.cs\" line 17 with condition \"hitCount == 3" +
                        "\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 19
        await testRunner.WhenAsync("the test target executes the \"loop\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 20
        await testRunner.AndAsync("I wait for a breakpoint hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 21
        await testRunner.ThenAsync("the breakpoint hit count should be 3", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Remove a breakpoint")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Remove a breakpoint")]
        public async global::System.Threading.Tasks.Task RemoveABreakpoint()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove a breakpoint", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 24
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 25
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 26
        await testRunner.AndAsync("a breakpoint on \"MethodTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 27
        await testRunner.WhenAsync("I remove the breakpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 28
        await testRunner.AndAsync("the test target executes the \"method\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 29
        await testRunner.ThenAsync("the debugger should not pause within 3 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Wait for breakpoint times out when no hit occurs")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Wait for breakpoint times out when no hit occurs")]
        public async global::System.Threading.Tasks.Task WaitForBreakpointTimesOutWhenNoHitOccurs()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Wait for breakpoint times out when no hit occurs", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 31
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 32
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 33
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 34
        await testRunner.ThenAsync("the debugger should not pause within 1 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Set exception breakpoint for InvalidOperationException")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Set exception breakpoint for InvalidOperationException")]
        public async global::System.Threading.Tasks.Task SetExceptionBreakpointForInvalidOperationException()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Set exception breakpoint for InvalidOperationException", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 36
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 37
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 38
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 39
        await testRunner.WhenAsync("I set an exception breakpoint for \"System.InvalidOperationException\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 40
        await testRunner.ThenAsync("the exception breakpoint should be set", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 41
        await testRunner.AndAsync("the exception breakpoint should be for type \"System.InvalidOperationException\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Exception breakpoint triggers on throw")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Exception breakpoint triggers on throw")]
        public async global::System.Threading.Tasks.Task ExceptionBreakpointTriggersOnThrow()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "5";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Exception breakpoint triggers on throw", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 43
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 44
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 45
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 46
        await testRunner.WhenAsync("I set an exception breakpoint for \"System.InvalidOperationException\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 47
        await testRunner.AndAsync("the test target executes the \"exception\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 48
        await testRunner.AndAsync("I wait for a breakpoint hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 49
        await testRunner.ThenAsync("the last hit should be an exception breakpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="List all breakpoints returns set breakpoints")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "List all breakpoints returns set breakpoints")]
        public async global::System.Threading.Tasks.Task ListAllBreakpointsReturnsSetBreakpoints()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "6";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("List all breakpoints returns set breakpoints", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 51
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 52
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 53
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 54
        await testRunner.AndAsync("a breakpoint on \"MethodTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 55
        await testRunner.AndAsync("a breakpoint on \"LoopTarget.cs\" line 17", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 56
        await testRunner.WhenAsync("I list all breakpoints", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 57
        await testRunner.ThenAsync("the breakpoint list should contain 2 breakpoints", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 58
        await testRunner.AndAsync("the breakpoint list should contain a breakpoint on \"MethodTarget.cs\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 59
        await testRunner.AndAsync("the breakpoint list should contain a breakpoint on \"LoopTarget.cs\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Enable and disable breakpoint toggle")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Enable and disable breakpoint toggle")]
        public async global::System.Threading.Tasks.Task EnableAndDisableBreakpointToggle()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "7";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Enable and disable breakpoint toggle", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 61
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 62
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 63
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 64
        await testRunner.AndAsync("a breakpoint on \"MethodTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 65
        await testRunner.WhenAsync("I disable the last set breakpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 66
        await testRunner.ThenAsync("the last set breakpoint should be disabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 67
        await testRunner.WhenAsync("I enable the last set breakpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 68
        await testRunner.ThenAsync("the last set breakpoint should be enabled", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Multiple breakpoints hit in order")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Multiple breakpoints hit in order")]
        public async global::System.Threading.Tasks.Task MultipleBreakpointsHitInOrder()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "8";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Multiple breakpoints hit in order", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 70
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 71
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 72
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 73
        await testRunner.AndAsync("a breakpoint on \"NestedTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 74
        await testRunner.AndAsync("a breakpoint on \"NestedTarget.cs\" line 23", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 75
        await testRunner.WhenAsync("the test target executes the \"nested\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 76
        await testRunner.AndAsync("I wait for a breakpoint hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 77
        await testRunner.ThenAsync("the debugger should pause at \"NestedTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 78
        await testRunner.WhenAsync("I continue execution", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 79
        await testRunner.AndAsync("I wait for a breakpoint hit", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 80
        await testRunner.ThenAsync("the debugger should pause at \"NestedTarget.cs\" line 23", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Disabled breakpoint does not trigger")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Disabled breakpoint does not trigger")]
        public async global::System.Threading.Tasks.Task DisabledBreakpointDoesNotTrigger()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "9";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Disabled breakpoint does not trigger", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 82
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 83
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 84
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 85
        await testRunner.AndAsync("a breakpoint on \"MethodTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 86
        await testRunner.WhenAsync("I disable the last set breakpoint", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 87
        await testRunner.AndAsync("the test target executes the \"method\" command", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 88
        await testRunner.ThenAsync("the debugger should not pause within 2 seconds", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::Xunit.SkippableFactAttribute(DisplayName="Remove breakpoint by ID removes from list")]
        [global::Xunit.TraitAttribute("FeatureTitle", "Breakpoints")]
        [global::Xunit.TraitAttribute("Description", "Remove breakpoint by ID removes from list")]
        public async global::System.Threading.Tasks.Task RemoveBreakpointByIDRemovesFromList()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "10";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Remove breakpoint by ID removes from list", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 90
    this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 91
        await testRunner.GivenAsync("a running test target process", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 92
        await testRunner.AndAsync("the debugger is attached to the test target", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 93
        await testRunner.AndAsync("a breakpoint on \"MethodTarget.cs\" line 14", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 94
        await testRunner.AndAsync("a breakpoint on \"LoopTarget.cs\" line 17", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 95
        await testRunner.WhenAsync("I list all breakpoints", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 96
        await testRunner.ThenAsync("the breakpoint list should contain 2 breakpoints", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 97
        await testRunner.WhenAsync("I remove the first breakpoint by ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 98
        await testRunner.AndAsync("I list all breakpoints", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
#line 99
        await testRunner.ThenAsync("the breakpoint list should contain 1 breakpoints", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, global::Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BreakpointsFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task global::Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BreakpointsFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
